'use strict';

angular.module('dyplomApp')

	.service('doctorsFactory', function(){ 
			
		 var doctors=[
                         {
                          name:"dr.danielle, m.d.",
                          description:"A trusted, patient focused and experienced locum doctor with a long history of serving patients by successfully diagnosing, treating and also managing their illnesses and diseases having rich experience of 3+ years as a surgeon. Experience in diagonsing the disease and providing best medical help. Expert in maintaining the daily report of patients.",
                          img:"images/doc-list1.png"
                         },
                        {
                          name:"dr. house, m.d.",
                          description:"Provide consultation over phone. Give Approvals to the prescriptions generated by the Paramedics with the help of a simple e-Diagnosis system.Ensure appropriate delivery of medical services by the paramedics and field staff.Consult the patients in Health Camps conducted in villages (for 5 - 10 days every month, will be assisted by a team of field workers).",
                          img:"images/doc-list2.png"
                         },
                         {
                          name:"dr. madison, m.d.",
                          description:"Data/Report maintenance and analysis. Act as a point of contact for the Head office. Give inputs for the field and Back end operations and help in the implementation of the same.Training of the other medical staff (as and when required). Training of the field staff (as and when required). Provide consultation over phone.",
                          img:"images/doc-list3.png"
                          },
                          {
                          name:"dr. gront, m.d.",
                          description:"Determined, diligent and committed. Flexible, adaptable, and sincere. Excellent inter personal communication skills. Strong interpersonal and relationship building skills. A team player :work in harmony with staff, administration to ensure high quality consistent with organizational procedures. Provide consultation over phone.",
                          img:"images/doc-list4.png"
                         },
                         {
                          name:"dr. makeland, m.d.",
                          description:"Attended international seminar by Dr Ean Scholten.Attended various state and district level seminars. Interviewed more than 20 medical talks of eminent doctors in All India radio. Working as chief medical officer at ASD medical center from Jan 2010 - Till Now. Worked as Consultant physician at RTY Hospital from July 2006 - Dec 2009.",
                          img:"images/doc-list5.png"
                         }

             ]
         
         
         
                        this.getDoctors = function(){  
                                return doctors;  
                        };
    
         });